name: Update release version.

permissions:
   contents: write
   pull-requests: write

on:
  release:
    types: [published]


jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v4
        with:
          fetch-depth: 0
      - name: Run release-tagger
        uses: tj-actions/release-tagger@edf6289ce260a5210863a9f1c0a2c1306f71525f # v6.0.0
      - name: Sync release version.
        uses: tj-actions/sync-release-version@2a7ef0deb39b3ecce887ee99d2261c6cef989d84 # v13.16
        id: sync-release-version
        with:
          pattern: '${{ github.repository }}@'
          only_major: true
          use_tag_commit_hash: true
          paths: |
            README.md
      - name: Run git-cliff
        uses: tj-actions/git-cliff@679041f051a4d2ab452f7e5e7b0eed2abee21131 # v2.2.0
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0 # v8.1.0
        with:
          base: "main"
          labels: "merge when passing"
          sign-commits: true
          title: "Upgraded to ${{ steps.sync-release-version.outputs.new_version }}"
          branch: "upgrade-to-${{ steps.sync-release-version.outputs.new_version }}"
          commit-message: "Upgraded from ${{ steps.sync-release-version.outputs.old_version }} -> ${{ steps.sync-release-version.outputs.new_version }}"
          body: "View [CHANGES](https://github.com/${{ github.repository }}/compare/${{ steps.sync-release-version.outputs.old_version }}...${{ steps.sync-release-version.outputs.new_version }})"
          token: ${{ secrets.GITHUB_TOKEN }}
